ucsb-cs156/proj-frontiers

frontend/src/fixtures/currentUserFixtures.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/Nav/GithubLogin.js
frontend/src/stories/components/Nav/AppNavbar.stories.js
frontend/src/stories/components/Nav/GithubLogin.stories.js
frontend/src/tests/components/Nav/GithubLogin.test.js
frontend/src/tests/components/Nav/GoogleLogin.test.js

In this PR, we add a button to the Navigation bar that appears only when the user is logged into Google first.
This button starts the Github OAuth flow to login to Github.
When Github is logged in, instead of showing the Connect Github button, the navigation bar shows the github login.
Logged out: 
Logged In:
Logged Out: 
Logged in to Google, but not Github:
Logged into both:

Pc GitHub login button

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java

In this PR, we refactor the courseId parameter; previously it was inconsistent (`courseId` vs. `course_id`).

pc - refactor courseId param (old name course_id)

---

src/main/java/edu/ucsb/cs156/frontiers/entities/Course.java
src/main/java/edu/ucsb/cs156/frontiers/entities/User.java

In this PR, we put `@JsonIgnore` on two fields to repair an emergency infinite loop in the json serialization.

pc - hotfix to repair infinite loop in json serialization

---

.github/workflows/13-backend-incremental-pitest.yml
.github/workflows/14-backend-pitest.yml
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/main/java/edu/ucsb/cs156/frontiers/services/UpdateUserService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/UpdateUserServiceTests.java

This PR addresses two issues:
* when an egrades file contains an `@umail.ucsb.edu` address, it needs to be converted into a `@ucsb.edu` address.
* RosterStudents and Users should be linked when a new User is created and when a RosterStudent is created or updated.
Deployed at: https://frontiers-qa.dokku-00.cs.ucsb.edu

pc - add code to fix umail addresses, handle upserts, and link users at upload time

---

.env.SAMPLE
docs/github-app-setup-localhost.md
src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/main/java/edu/ucsb/cs156/frontiers/errors/InvalidInstallationTypeException.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationLinkerService.java
src/main/resources/application.properties
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationLinkerServiceTests.java

In this PR, I add the ability to link a course and a github app installation together. There are two endpoints for this: one external redirect to github, with the courseId saved as the state, and an incoming one where Github provides the installation id.
Since students will not be admins on the github organization as they write code, there is a carveout in the incoming endpoint, where it simply informs students they don't have the permissions to link the two together. The `/api/courses/link` endpoint also redirects, but to the frontend depending on whether it was successful or not.
The steps for creating an app are documents in docs/github-app-setup-localhost.md
Currently deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/
Merge before #40.

Adding the Ability to Link a Course to a Github App Installation

---

src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerDetailedTests.java

In this PR, I remove the "completed" return of the updateAllRosters test. This is because it creates a race condition -- since the test completes almost instantly, it occasionally returns completed rather than running, failing the test. As a result, I remove the "completed" save return, ensuring that it returns "running." The job actually running and completing is verified in a different file.

Fixing a Flaky Job Test

---

src/main/java/edu/ucsb/cs156/frontiers/config/SecurityConfig.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/WebhookController.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/CourseRepository.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/RosterStudentRepository.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/UserRepository.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/WebhookControllerTests.java

In this PR, I add the ability for the application to accept webhooks from GitHub.
In this case, it is used for detecting accepted membership invites.
In order to allow the request to be successful, I disable CSRF-protection on the endpoint to prevent GitHub from being marked unauthorized.
The webhook URL is /api/webhooks/github.
Has full test and mutation coverage. Merge after #21 
Deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/

Adding the Ability to Accept Webhooks

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
src/main/java/edu/ucsb/cs156/frontiers/errors/NoLinkedOrganizationException.java
src/main/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJob.java
src/main/java/edu/ucsb/cs156/frontiers/services/RepositoryService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/ApiControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/DummyController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJobTest.java
src/test/java/edu/ucsb/cs156/frontiers/services/RepositoryServiceTests.java

In this PR, I add the ability to create student repos. Once a course is linked to an organization, any RosterStudent with a linked User with a GithubLogin and the status of MEMBER will have a repository created for them. This is achieved by the endpoint starting a job. The Job picks students with the above qualities, and runs a service, which will check if the repo exists, if not create it, then add the student as a collaborator.
This is currently deployed to https://frontiers-qa.dokku-00.cs.ucsb.edu/ -- I have Sangita and I set up as students that are listed as invited for Course 2, for testing purposes. It should create two repos with the prefix listed in ucsb-cs156.
Kills all mutations and has 100% line coverage. Merge after #21.

Creating Simple Student Repos

---

.gitignore

In this PR, we add `*.pem` files and `pkcs8.key` to the `.gitignore`
.pem files are private keys downloaded from Github as part of the installation process for a Github App.
It is important that they not get committed to the repo accidentally.

pc - don't store .pem files in the repo

---

docs/github-app-setup-dokku.md

In this PR, I write a set of instructions for creating a GitHub app on Dokku. These instructions are largely based on the set I wrote for my Authentication Spike (https://github.com/Division7/AuthSpike) with the tweaks required to add webhooks.

Adding the instructions for creating a Github App on Dokku

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/main/java/edu/ucsb/cs156/frontiers/jobs/UpdateOrgMembershipJob.java
src/main/java/edu/ucsb/cs156/frontiers/models/OrgMember.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/UserRepository.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/UpdateOrgMembershipJobTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java

In this PR, I create a job under `RosterStudentsController` that will take students with a linked user and github login, and if they are present in the organization, marks the Roster Student as `OrgStatus.MEMBER`
Currently deployed to https://frontiers-qa.dokku-00.cs.ucsb.edu/
I successfully ran the job against Course 1, and each student is marked as member, other than the two students who linked a separate account on Frontiers than using the membership script.
Notable issue:
If two accounts have the same GitHub account linked, the job will throw an error. I'm unsure if I should simply account for this here or prevent two accounts from linking the same GitHub account.

Adding a Job to Mark Linked Users as Members

---

frontend/.gitignore
frontend/src/fixtures/coursesFixtures.js
frontend/src/main/components/Courses/CoursesTable.js
frontend/src/stories/components/Courses/CoursesTable.stories.js
frontend/src/tests/components/Courses/CoursesTable.test.js

Closes #57 
In this PR we add a CoursesTable component, plus tests and storybook.
This PR changes nothing in the active app; this is a component for future use in creating a Courses Index Page.
Link to Storybook: <https://67da6ee1a47bfcdda4700814-zzasiwkikr.chromatic.com/?path=/story/components-courses-coursestable--three-courses-with-install-button>
Screenshot:

Pc - add courses table component (frontend component for storybook only)

---

frontend/package.json

In this PR, we fix a problem that can crop up if you have a `build` directory under `frontend`, which can happen if you've been running end2end tests recently.
Suddenly, eslint has a cow, and there are thousands of errors!  
This is because eslint is trying to do linting on all kinds of code that you didn't write, that happens to live the `build` directory.
This small change to `package.json` tells eslint to ignore the `build` directory,

pc - eslint should ignore build directory

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/Courses/CoursesIndexPage.js
frontend/src/tests/pages/Courses/CoursesIndexPage.test.js

This PR creates the courses index page and tests, at the route `admin/courses` under the admin tab in the navbar.
Screenshot from localhost test:
Closes #60

Create Courses Index Page and Tests

---

pom.xml

In this PR, we correct the artifact name to `frontiers` from `team01`, which I missed in #50.
Merge before #64, #65

Fixing the Maven Artifact

---

src/main/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJob.java
src/main/java/edu/ucsb/cs156/frontiers/services/JwtService.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
src/main/java/edu/ucsb/cs156/frontiers/services/RepositoryService.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJobTest.java
src/test/java/edu/ucsb/cs156/frontiers/services/JwtServiceTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/RepositoryServiceTests.java

In this PR, I move the responsibility to check for whether or not a course has a linked GitHub Organization to the `JwtService`. This ensures that before calling the actual GitHub API, regardless of the controller behavior, an exception will be thrown if `installationId` or `orgName` is null. This exception is handled by `ApiController`, to provide a centralized response to the application being thrown. Endpoints that create jobs that access the GitHub API should still check to see whether or not there is a linked organization prior to the job being ran, but this at least provides a backstop to ensure that faulty API calls will not be made.
Deployed to https://frontiers-qa.dokku-00.cs.ucsb.edu/

Moving the Installation Check to JwtService

---

src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerDetailedTests.java

In this PR, I attempt to kill the flaky job test that sometimes returns "complete" or "running" once and for all.
However, since I am unable to directly mock JobService, I simply use matchers to compare the value to either "running" or "complete", as they are both acceptable answers.

Killing the Flaky Job Test Once and For All

---

src/main/java/edu/ucsb/cs156/frontiers/entities/RosterStudent.java
src/main/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTO.java
src/test/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTOTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/RosterStudentDTOServiceTests.java

In this PR, I replace RosterStudent and RosterStudentDTO's primitive githubId int with Integer, in order to allow null values in the database.
I will add an issue to do the same for Users so that there is parity, as there is not enough time to do so right now.
Deployed to https://frontiers-daniel.dokku-00.cs.ucsb.edu/

Replacing RosterStudent & RosterStudentDTO int with Integer

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

This PR is a HOTFIX to correct an incorrect redirect URL.
After the callback for the  installation of the github app, the courses controller was redirecting to a non existing page: 
`/courses/success`
Instead, we should redirect to the page you were on (`/admin/courses`), and add parameters to indicate success and which course was updated.
Those can be used in future work to provide a nice message indicating that the github app installation was successful.

HOTFIX - fix redirect after github app install

---

.gitignore
docs/github-app-setup-dokku.md
docs/github-app-setup-localhost.md
keyconvert.sh

In this PR, I add the `./keyconvert.sh` script which ensures that the key the script is run on exists, as the `openssl` command will output a key whether or not there is an input.
I add all `.pem` and `.key` files to gitignore, and update the directions to match the new script.

Fixing the OpenSSL Command

---

src/main/java/edu/ucsb/cs156/frontiers/repositories/AdminRepository.java
src/main/java/edu/ucsb/cs156/frontiers/services/GoogleSignInServiceImpl.java

In this PR, I enable adding admins by email, building off of team 7's work on managing admin emails.
I achieve this by replacing the static `ADMIN_EMAILS` variable in the GoogleSignInServiceImpl with the AdminRepository, which has existsByEmail added as a method.
Currently deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/

Enabling Admin Role by Email

---

.github/CODEOWNERS

In this PR, we update CODEOWNERS to Phill, Daniel and Divy for Summer 2025.
These are the users that will be automatically requested for code reviews.

pc - update CODEOWNERS to Phill, Daniel and Divy for Summer 2025

---

frontend/src/fixtures/coursesFixtures.js
frontend/src/main/components/Courses/AdminCoursesTable.js
frontend/src/main/components/Courses/CoursesTable.js
frontend/src/main/pages/Courses/CoursesIndexPage.js
frontend/src/stories/components/Courses/AdminCoursesTable.stories.js
frontend/src/stories/components/Courses/CoursesTable.stories.js
frontend/src/tests/components/Courses/AdminCoursesTable.test.js
frontend/src/tests/components/Courses/CoursesTable.test.js
frontend/src/tests/pages/Courses/CoursesIndexPage.test.js

Closes #70 
This PR supports the user stories:
* As a student, 
* I can see the courses for which I appear on the roster, and my status in each course
* So that I can click to join the github organization for courses where I haven't done that yet.
* As a staff member
* I can see the courses where I've been listed as a staff member, and my status in those github orgs, * So that I can click to join the github orgs.
The new React component in this PR will be useful in building that page, which will likely become the new default home page after logging in to the app.
In this PR we:
* rename the existing React component `CoursesTable` to `AdminCoursesTable`
* This one is used only for pages that are Admin/Instructor facing
* create a new React component called `CoursesTable` that is used for …

pc - Student/Staff facing course table

---

src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerDetailedTests.java

In this PR, I finally kill the flaky job test once and for all by appropriately attributing the status to "complete" rather than "completed"
Merge before #149.

Killing The Flaky Job Test

---

src/main/java/edu/ucsb/cs156/frontiers/services/CurrentUserServiceImpl.java

In this PR, I flatten the role hierarchy on the frontend so that we don't have to transmit or update the hierarchy on the frontend.
Merge after #150.
Currently deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/
Despite solely being tagged with the admin role, the following roles now appear on the frontend:

Flattening the Role Hierarchy on the Frontend

---

src/main/java/edu/ucsb/cs156/frontiers/services/JwtService.java
src/test/java/edu/ucsb/cs156/frontiers/services/JwtServiceTests.java

At some point, GitHub transitioned to using installation IDs rather than org names for generating tokens.
This updates JWTService to match the new standard.

Fixing JwtService

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/ApiControllerTests.java

In this PR, we add methods to the Api controller that allow us to check whether the current user has a specific role.   
These methods are aware of the role hierarchy.
These methods are useful for modifying endpoints to, for example, making the /api/courses endpoint:
* For ROLE_ADMIN, return all courses
* For ROLE_INSTRUCTOR, return only the courses that the instructor has access to.

pc - add methods for roles to ApiController

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/JobsController.java
src/main/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJob.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerDetailedTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerJobsTests.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJobTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java

In this PR, I implement a job that audits the status of each course, and ensures that students who have joined the course on GitHub are marked as MEMBER.
This runs on every course with an installation id and organization name.
Currently deployed to https://frontiers-daniel.dokku-00.cs.ucsb.edu/
Closes #157 
Merge after #154

JOB - Async job that updates all student github org membership statuses

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/main/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTO.java
src/main/java/edu/ucsb/cs156/frontiers/services/RosterStudentDTOService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTOTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/RosterStudentDTOServiceTests.java

In this PR, we refactor the RosterStudentDTO to make it a record instead of a Lombok Data Class.
This simplifies mutation coverage and reduces boilerplate code.

REFACTOR: refactor the RosterStudentDTO to make it a record instead of a Lombok Data Class

---

src/main/resources/db/migration/changes/011-Update-None-To-Pending.json

In this PR, I add a liquibase migration file to update all instances of RosterStudents at NONE to PENDING.
Currently, this prevents users with attached Roster Students at the status NONE from signing in.
1. Inspect the database frontiers-qa-test-db2 with `dokku postgres:connect frontiers-qa-test-db2`.
2.  With the following command, observe that there are Roster Students with the status NONE:
`SELECT * FROM ROSTER_STUDENT`
3. Unlink frontiers-qa-test-db1 from frontiers-qa (`dokku postgres:unlink frontiers-qa-test-db-1 frontiers-qa --no-restart`)
4. Link frontiers-qa-test-db2 to frontiers-qa. (`dokku postgres:link frontiers-qa-test-db2 frontiers-qa`)
5. Then, sign into frontiers-qa, and using swagger, look to make sure there are no errors with any roster students.
Deployed to …

Hotfix to Update OrgStatus from NONE to PENDING in the Prod/QA databases

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/WebhookController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/WebhookControllerTests.java

In this PR, I enable marking RosterStudents as Owner on a member invite webhook from GitHub.
Closes #169 
Deployed to https://frontiers-qa1.dokku-00.cs.ucsb.edu/
1. Make a course with a linked github org
2. Add a roster student that corresponds to a real github user
3. Invite that github user as an owner.  (Not sure if the webhook will change status to INVITED, but check if it does).
4. Have that github user accept the invitation
5. The roster student's status should now show as OWNER.

Marking Students as Owners Via Webhook

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/main/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTO.java
src/main/java/edu/ucsb/cs156/frontiers/models/UserDataDTO.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/RosterStudentRepository.java
src/main/java/edu/ucsb/cs156/frontiers/services/RosterStudentDTOService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTOTests.java
src/test/java/edu/ucsb/cs156/frontiers/models/UserDataDTOTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/RosterStudentDTOServiceTests.java

MERGE AFTER #184 (the refactor is needed for this PR to pass pitest mutation coverage)
Closes #180 and, when #179 also merged, also #46.
We do not want duplicate entries for the same student in a course.  Both email and studentId should be unique, but in the event of human error that results in entry of a duplicate value, we want to handle that gracefully.
The main way that duplicate might arise in practice are:
* Manually entering duplicates through the single add POST
* Having duplicate lines in a manually edited CSV file
* Entering someone manually by POST that was already entered via the CSV upload.
Try all of the scenarios above, and ensure that in each one, the result is something reasonable.
Deployed to: https://frontiers-qa4.dokku-00.cs.ucsb.edu

pc - ensure that within a course, RosterStudent records have unique email and unique studentId values

---

frontend/.storybook/main.js
frontend/.storybook/preview.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/main/components/Courses/InstructorCoursesTable.js
frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/stories/pages/Instructor/InstructorCourseShowPage.stories.js
frontend/src/tests/components/Courses/InstructorCoursesTable.test.js
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

Deployed to: https://frontiers-qa5.dokku-00.cs.ucsb.edu
In this PR, we add a show page for the course.
For now, this page just repeats information already available on the InstructorCoursesTable, but in the future, it will be a basis for adding more instructor facing features, such as:
* maintaining the list of roster students
* creating repos for individual and team assignments
* anything else an instructor needs to do that pertains to a specific course.
Modified InstructorCoursesTable, where course title is a link:
When you click on the link, you go to pages such as these:

FEATURE: instructor course show page

---

src/main/java/edu/ucsb/cs156/frontiers/utilities/CanonicalFormConverter.java
src/test/java/edu/ucsb/cs156/frontiers/utiltiies/CanonicalFormConverterTests.java

Closes #179 
In this PR, we introduce a utility to the backend called CanonicalFormConverter.
This is for isolating code for various hacks such as converting @umail.ucsb.edu to @ucsb.edu
We may not be able to avoid including special case code for various universities completely.  But we can at least isolate it in one part of the code so that it doesn't spread all over the place.
Deployed to https://frontiers-qa.dokku-00.cs.ucsb.edu
This is mostly a refactor, but there is one user facing change to test:
* As an admin, try enter email addresses containing `@umail.ucsb.edu` as admins or instructors (note that this would be unlikely to ever occur in practice, but it is not impossible.). They should automatically convert to @ucsb.edu addresses.

REFACTOR: add a utility to isolate the hacks for email addresses

---

src/main/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJob.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJobTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java

In this PR, I make the MembershipAuditJob appropriately check for students that are currently invited to the organization, and mark them as such. Closes #170 
In addition to adding the necessary unit tests, I remove comments for test code that is self-defining.
Test Plan:
1. Make a course with a linked github org
2. Add a roster student that corresponds to a real github user
3. Invite that github user (whether using the app or simply GitHub, it shouldn't matter)
4. Run MembershipAuditJob and ensure they continue to be marked as INVITED.
Deployed to https://frontiers-qa2.dokku-00.cs.ucsb.edu

Appropriately Marking Students as Invited in MembershipAuditJob

---

.env.SAMPLE
.gitignore
docs/github-app-setup-dokku.md
docs/github-app-setup-localhost.md
keyconvert-localhost.sh
keyconvert.sh

In this PR, we rewrite the scripts and the instructions
for installing the Github App.   Instead of passing the name of
the private key file, we just find it automatically; if there is
more than one, we prompt the user to select one.
We have separate scripts for localhost and dokku.
The localhost version just creates the secrets.yaml file directly (warning the user if it is overwriting another one).
The dokku version gives the exact command to copy/paste to the dokku command line.
The instructions have been modified to match these changes t to the scripts, and have been streamlined to avoid duplicating instructions that already appear elsewhere.
1. Try setting up a new installation of frontiers on localhost, following the instructions and using the script.
2. Try setting up a new …

pc - rewrite scripts and instructions for converting the private key for the Github app

---

src/main/java/edu/ucsb/cs156/frontiers/config/CourseSecurity.java
src/main/java/edu/ucsb/cs156/frontiers/config/SecurityConfig.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
src/test/java/edu/ucsb/cs156/frontiers/ControllerTestCase.java
src/test/java/edu/ucsb/cs156/frontiers/annotations/WithInstructorCoursePermissions.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/security/CourseSecurityTests.java
src/test/java/edu/ucsb/cs156/frontiers/security/DummyCourseSecurity.java
src/test/java/edu/ucsb/cs156/frontiers/testconfig/TestCourseSecurity.java

In this PR, I create a Spring Security annotation designed to factor out Spring Security annotations. It is designed to be used on methods that require a Course Id.
However, this method is inefficient because it has to call the database for the Current User, and the Course objects again.
In the future, this can be mitigated by using a Spring Boot converter, so that handling of returning a Course object is centrally handled.
As a proof of concept, this is applied to createStudentRepos.
Currently synced to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/
Closes #167

Factoring Out Course Permissions Management

---

frontend/src/main/components/Courses/CourseModal.js
frontend/src/main/pages/Instructors/CoursesIndexPage.js
frontend/src/stories/components/Courses/CourseModal.stories.js
frontend/src/tests/components/Courses/CourseModal.test.js
frontend/src/tests/pages/Instructors/CoursesIndexPage.test.js
src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

In this PR, I allow the creation of courses via the modal created in #199. This is added to the Instructors' course page.
For simplicity and to keep the number of fixtures down, `/api/courses/post` now returns an InstructorCourseView record.
Modal in action:
After submit:
Deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/
Closes #134, merge after #199

Allowing Course Creation

---

pom.xml

In this PR, I update the pom.xml to only run `npm ci` and `npm run build` when there have been changes to files in the frontend, as well as `package.json` and `package-lock.json`
Basis of changes came from this chat: https://claude.ai/share/36f6a20d-11db-4d5f-9daa-87cc154e90bd
Stolen directly from https://github.com/ucsb-cs156-s25/STARTER-team02/pull/78

Improving Integration Test Speed

---

frontend/src/App.js
frontend/src/main/layouts/BasicLayout/BasicLayout.js
frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/main/pages/Instructors/CoursesIndexPage.js
frontend/src/main/pages/ProfilePage.js
frontend/src/main/utils/currentUser.js
frontend/src/tests/utils/currentUser.test.js

In this PR, I place `useCurrentUser()`'s `useQuery()` call inside of a variable so that I can only return the data. This eliminates a possible difference to make `useCurrentUser` easier to use, at the cost of hiding the query status.
This PR is fractured into two commits so that the first commit can be cherry-picked for other projects, though those projects will also have to update their specific `useCurrentUser()` usages.
Deployed to https://frontiers-qa1.dokku-00.cs.ucsb.edu/
Closes #197, merge after #200 (I thought it would involve useCurrentUser, noticed it didn't after rebase)

Refactoring the Frontend Current User Structure

---

src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationLinkerService.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationLinkerServiceTests.java

In this PR, I add a method that will uninstall Frontiers from a GitHub organization.
In the case where the installation Id or org name isn't present, it returns prematurely.
This is prep for #132 
Deployed to https://frontiers-qa2.dokku-00.cs.ucsb.edu/

Adding a Service to Delete a Frontiers Installation

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

In this PR, I add an endpoint to delete a course.
It can only be ran by someone with permission to manage the course, and will attempt to uninstall Frontiers from the organization if linked.
Deployed to https://frontiers-qa2.dokku-00.cs.ucsb.edu/
Test plan:
1. Create a course
2. Link it to a GitHub Organization
3. Add a Roster Student
4. Add a CourseStaff
5. Attempt to delete the course
6. Ensure that the frontiers app is also no longer installed on GitHub.
Closes #132, Merge after #203

FEATURE: As an admin, I can delete a course, BACKEND only.

---

pom.xml
src/main/java/edu/ucsb/cs156/frontiers/config/SecurityConfig.java
src/main/java/edu/ucsb/cs156/frontiers/models/SystemInfo.java
src/main/java/edu/ucsb/cs156/frontiers/services/GoogleSignInServiceImpl.java
src/main/java/edu/ucsb/cs156/frontiers/services/SystemInfoServiceImpl.java
src/main/java/edu/ucsb/cs156/frontiers/startup/AzureProfileEnabler.java
src/main/resources/META-INF/spring.factories
src/main/resources/application-microsoft.properties
src/test/java/edu/ucsb/cs156/frontiers/services/SystemInfoServiceImplTests.java

In this PR, I add access to Azure Active Directory.
This is achieved by creating a custom issuer validator, as Microsoft will give different issuers depending on who the tenant is.
To prevent students from requiring an Azure account and a working setup, this is configured to remain gated behind the Spring Profile "microsoft" -- it is programatically enabled when the environment variable MICROSOFT is set to true.
The code for doing so (`AzureProfileEnabler`) is exempted from line coverage and unit testing since I'm not exactly sure how to test it.
Included also is a change to `GoogleSignInServiceImpl` to prevent duplicate accounts from being created if a user signs in with both Google & AD with the same email.
Deployed to https://frontiers-daniel.dokku-00.cs.ucsb.edu/
Changes to the …

Adding Azure Active Directory as a Sign-On

---

frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/main/utils/useBackend.js
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
frontend/src/tests/utils/useBackend.test.js

In this PR, I handle the backend returning a "Not Found" on the CourseShowPage.
If the useBackend() query fails, a modal will be displayed informing the user that the course does not exist.
I decided against making this modal into a proper component because it is essentially a straight bootstrap modal with some text in it.
After 3 seconds, it will return them to the Instructors' Course list.
Test Plan:
1. Sign in as an account with instructor permissions
2. Go to the url of a nonexistent course, like https://frontiers-qa4.dokku-00.cs.ucsb.edu/instructor/courses/47
3. Observe the modal and the change of pages.
Deployed to https://frontiers-qa4.dokku-00.cs.ucsb.edu/
Closes #206

Handling Not Found on the CourseShowPage

---

frontend/package-lock.json
frontend/package.json
frontend/src/main/components/Auth/SignInCard.js
frontend/src/stories/components/Auth/SignInCard.stories.js
frontend/src/tests/components/Auth/SignInCard.test.js

In this PR I add a sign in card that can be used for various OIDC sign-in methods.
Storybook link: https://67da6ee1a47bfcdda4700814-qznveqhnvc.chromatic.com/?path=/story/components-auth-signincard--google
Additionally, this PR adds [React-Icons](https://react-icons.github.io/react-icons/), a popular icon bundler for React, for the Google and Microsoft logos.

Adding a Sign In Card for Use on the Sign In Page

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

In this PR, we add a field to each of two API endpoints as described below:
* For /api/courses/list, which is the endpoint where a student can see what courses they are on the roster of, we add rosterStudentId
* For /api/courses/staffCourses, which is the endpoint where a user can see what courses they are on the staff roster for, we add staffId
Both of these are in service of the same purpose: to make sure we have the id we need in order to implement the JoinCourse button, which needs these values to call the endpoints to join a course.
Deployed to: https://frontiers-qa1.dokku-00.cs.ucsb.edu

pc/dj - add rosterStudentId and staffId to the backend endpoints we use to populate home page so that we can join courses

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java

In this PR, I check the organization status of a user if joinCourse fails to invite them to the organization.
It checks to see and labels them appropriately if they are either an Owner or a Direct Member, and will warn if another unexpected role is used (I don't expect students to be marked as a billing manager, etc).
Previous changes from #212 are included so that all statuses can be updated in the same sweep.
Test plan:
1. Add a roster student to a linked course, with the owner of the roster student already being part of the organization
2. Have the roster student owner attempt to join the course
3. Check their status via swagger.
Closes #160, Merge after #212

Checking Organization Status on Invite Fail

---

src/main/java/edu/ucsb/cs156/frontiers/services/GoogleSignInServiceImpl.java
src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java

Currently, when joining a course, if a person is already an organization member, when pressing Join Course, it will error out. 
This is because the GitHub API returns "member" rather than "direct_member".
Additionally, I fix the check to see if githubId is set by checking now against null rather than 0.
This PR corrects this.

dj - fixed member inference to say member rather than direct_member

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubController.java
src/main/resources/application.properties
src/test/java/edu/ucsb/cs156/frontiers/controllers/GithubControllerTests.java

In this PR, I add a new Controller (`GithubController`) with a DELETE endpoint that disconnects a user account from GitHub.
Additionally, I manually configure the GitHub authorization url so that the user will be reprompted to authorize to GitHub every time they connect (so they can switch accounts if need be).
It is jointly deployed with #234 on https://frontiers-daniel.dokku-00.cs.ucsb.edu/
Test plan:
1. Log In
2. Link a GitHub Account
3. Go to the profile page
4. Unlink your github account
5. Make sure your credentials are gone.
Closes #161 with #234

Adding backend disconnect for GitHub accounts

---

pom.xml
src/main/java/edu/ucsb/cs156/frontiers/config/GithubGraphQLClientConfig.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLController.java
src/main/java/edu/ucsb/cs156/frontiers/errors/CourseNotAuthorized.java
src/main/java/edu/ucsb/cs156/frontiers/services/GithubGraphQLService.java
src/test/java/edu/ucsb/cs156/frontiers/config/GithubGraphQLClientConfigTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/ApiControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/GithubGraphQLServiceTests.java

In this PR, we create the backend only (a controller and a service) as a proof of concept for retrieving information from the Github GraphQL API.
This retrieves the "default branch name" for any repo, using the github credentials associated with the Github App installed for a particular course.
This is the first step towards being able to retrieve commits on the default branch of a repo.
1. Create a course an install the Github App
2. Remember the course id number (e.g. `1` in this example)
3. Navigate to Swagger to the endpoint shown
[`GET /api/github/graphql/defaultBranchName`](http://localhost:8080/swagger-ui/index.html#/GithubGraphQL/getDefaultBranchName)
4. Fill in the course Id number, and the owner (organization) and repo name for any public repo.
5. It should return the default …

FEATURE (BACKEND) - Proof of concept for GraphQL queries to Github (look up default branch name)

---

pom.xml
src/main/java/edu/ucsb/cs156/frontiers/config/GithubGraphQLClientConfig.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLController.java
src/main/java/edu/ucsb/cs156/frontiers/errors/CourseNotAuthorized.java
src/main/java/edu/ucsb/cs156/frontiers/services/GithubGraphQLService.java
src/test/java/edu/ucsb/cs156/frontiers/config/GithubGraphQLClientConfigTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/ApiControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/fixtures/GithubGraphQLFixtures.java
src/test/java/edu/ucsb/cs156/frontiers/services/GithubGraphQLServiceTests.java

Merge after #231   Closes #220
In this PR, we add an endpoint to get commits for a repo on any branch.
The endpoint exposes the paging that is a part of the graphql API; you can specify a `first` parameter, which gives you the first n commits after the "cursor".  Initially, the cursor should be empty; this is passed as the parameter `after`.   
In subsequent calls, if you copy/paste the value of the cursor, the call will start at that point.
1. Create a course an install the Github App
2. Remember the course id number (e.g. `1` in this example)
3. Navigate to Swagger to the endpoint shown
[`GET /api/github/graphql/defaultBranchName`](http://localhost:8080/swagger-ui/index.html#/GithubGraphQL/getDefaultBranchName)
4. Fill in values:
* course Id number, owner (organization), repo name, and …

FEATURE (BACKEND):  endpoint to get commits from Github GraphQL API

---

frontend/src/main/components/RosterStudent/RosterStudentForm.js
frontend/src/main/components/RosterStudent/RosterStudentTable.js
frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js

In this PR, I enable the callback for the edit button in RosterStudentsTable. This is based on #236 to how it will fit into the page.
Additionally, I modify RosterStudentForm to allow disabling of the cancel button for use in the modal.
Modal demonstration:
Test plan:
1. Add a roster student
2. Edit it
3. See that it has been updated in the RosterStudentTable on the CourseShowPage.
Merge after #236 
Contributes to #117 
Deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/

Enabling the Roster Student Edit Button

---

frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js

Closes #246 
Deployed to: https://frontiers-qa5.dokku-00.cs.ucsb.edu
In this PR we make a small tweak to the InstructorCourseShowPage so that we can see what course we are working with, regardless of which tab we are on.
https://67da6ee1a47bfcdda4700814-ogcmuffhsj.chromatic.com/?path=/story/pages-instructor-instructorcourseshowpage--example-course-no-students
https://www.chromatic.com/test?appId=67da6ee1a47bfcdda4700814&id=688149e9ad15109eda836e98
https://www.chromatic.com/test?appId=67da6ee1a47bfcdda4700814&id=688149e9ad15109eda836e99
https://www.chromatic.com/test?appId=67da6ee1a47bfcdda4700814&id=688149e9ad15109eda836ec1
https://67da6ee1a47bfcdda4700814-ogcmuffhsj.chromatic.com/?path=/story/pages-instructor-instructorcourseshowpage--example-course-no-students
Before:
After:

pc - put course title at top of page above the tabs on InstructorCourseShowPage

---

frontend/src/App.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/HomePageConnectGithub.js
frontend/src/main/pages/LoadingPage.js
frontend/src/stories/pages/HomePageConnectGithub.stories.js
frontend/src/stories/pages/HomePageLoggedIn.stories.js
frontend/src/tests/components/Nav/AppNavbar.test.js
frontend/src/tests/components/Nav/GithubLogin.test.js
frontend/src/tests/pages/HomePageConnectGithub.test.js

This PR addresses #229 
**This PR**:
- Adds the HomePageConnectGithub page (plus tests and stories).
- Updates App.js so that when a user is logged in, but has not yet connected their GitHub account they are directed to the HomePageConnectGithub.
- Updates the navigation bar so when on the user is on the HomePageConnectGithub page they do not see the connect github button. 
- Updates testing for AppNavBar and GithubLoginTest to cover a mutation. 
- Does very small changes to HomePageLoggedIn stories and the loading page to clean up the files.
**Dokku**: https://frontiers-divyanipunj.dokku-00.cs.ucsb.edu/
**Storybook**: https://67da6ee1a47bfcdda4700814-sfhuewtuer.chromatic.com/?path=/story/pages-homepageconnectgithub--no-git-hub-regular-user
**NOTES/DISCUSSION**: The user will not be able …

divyanipunj -  Added HomePageConnectGithub Component and Updated Related Files

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java

In this PR, I loosen the permissions on who is allowed to create student assignment repositories in a GitHub organization.
Previously, it was restricted to the creator only -- now, the creator or an administrator can create repositories (via `CourseSecurity`)
Jointly deployed with #257 to https://frontiers-qa1.dokku-00.cs.ucsb.edu/

Loosening the Assignment Repo Permissions

---

frontend/package-lock.json

In this PR, I de-dupe package-lock.json so that the frontiers can start on localhost. 
Prior to the change, running `npm start` after `npm ci` results in this:
After running `npm dedupe`, the application starts.
Solution documented here: https://github.com/storybookjs/storybook/issues/17049#issuecomment-1202121109

[HOTFIX] de-duping package-lock

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/WebhookController.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/CourseStaffRepository.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/WebhookControllerTests.java

In this PR, I add the requisite code to handle CourseStaff invitations and GitHub organization joins.
It's mostly a copy-and-paste of the code for RosterStudents.
Testing Plan:
1. Create a course and link it to a GitHub organization
2. Add someone as a CourseStaff member
3. Have them Join Course, and accept the invitation
4. Verify their status is now properly set
Deployed to https://frontiers-qa2.dokku-00.cs.ucsb.edu/

Adding Staff Webhooks

---

frontend/src/fixtures/usersFixtures.js
frontend/src/main/components/Users/UsersTable.js
frontend/src/stories/components/Users/UsersTable.stories.js
frontend/src/tests/components/Users/UsersTable.test.js

In this PR, I add the column "Instructor" to the users table, displaying whether or not a user is displayed in the Instructors table. The backend was already present, so I simply added the frontend.
While working with the Users table, I added the appropriate storybook.
No merge conflicts with #261, #262 - I modified different files.
Storybook: https://67da6ee1a47bfcdda4700814-pnpjwiewvf.chromatic.com/?path=/story/components-users-userstable--three-items
Closes #173

Adding Instructors to the Users Table

---

frontend/src/main/components/Common/OurPagination.js
frontend/src/main/pages/Admin/AdminUsersPage.js
frontend/src/stories/components/Common/OurPagination.stories.js
frontend/src/stories/pages/Admin/AdminUsersPage.stories.js
frontend/src/tests/components/Common/OurPagination.test.js
frontend/src/tests/pages/Admin/AdminUsersPage.test.js
src/main/java/edu/ucsb/cs156/frontiers/FrontiersMain.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/UsersController.java
src/main/java/edu/ucsb/cs156/frontiers/repositories/UserRepository.java
src/main/java/edu/ucsb/cs156/frontiers/services/UserDataDTOService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/UsersControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/UserDataDTOServiceTests.java

In this PR, I paginate the Users table, bringing over [proj-courses' OurPagination Component](https://github.com/ucsb-cs156/proj-courses/blob/main/frontend/src/main/components/Utils/OurPagination.js), with some tweaks to align with React principles. 
It is deployed in a div that is centered in the middle of the Users page. Currently has a static size of 50 and is sorted by ID. (Adding sort/size may be good for a student?)
Notably, I add the `@EnableSpringDataWebSupport(pageSerializationMode=VIA_DTO)` annotation to the application, to comply with Spring Data's notes on using `PageImpl<>`. They are automatically converted to `PagedModel`, rather than having to manually apply the conversion.
If the request does not request pagination, Spring returns `Pageable.unpaged()` by default. …

Paginating the Users Table (One Consolidated PR)

---

frontend/src/main/components/Courses/InstructorCoursesTable.js
frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/pages/Admin/AdminsIndexPage.js
frontend/src/main/pages/Admin/InstructorsIndexPage.js

In this PR, I replace the href attributes in the Navbar and on various buttons with the `React-Router-Dom` `Link` instead to prevent unnecessary full-context reloads.
Since these are internal to the site, they should be navigation calls, rather than hrefs, which will cause the entire application to reload.
Testing Plan:
1. Try the urls on the navbar - make sure they still work.
2. Try out a link in a table and make sure they still work. 
Prep work for #242

Enforcing Internal React Router Navigation

---

.github/workflows/13-backend-incremental-pitest.yml
.github/workflows/14-backend-pitest.yml

In this PR, we change two of the CI/CD workflows so that slashes in the branch name won't cause them to fail.
This is necessary to support the AI assistant Junie.

pc - update workflows 13 and 14 to tolerate slashes in the branch name by changing them to hyphens

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
src/main/java/edu/ucsb/cs156/frontiers/enums/RepositoryPermissions.java
src/main/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJob.java
src/main/java/edu/ucsb/cs156/frontiers/services/RepositoryService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJobTest.java
src/test/java/edu/ucsb/cs156/frontiers/services/RepositoryServiceTests.java

In this PR, I allow the customizing of permissions levels when creating repositories for Students.
These are contained in an enum, with the constant being the user-friendly definition, and a method to get it's name in the GitHub API.
Additionally, I move the part where it sets the permissions level for students to run regardless of if the repo is created or not.
If the student is already added as a collaborator, the returned `204 (No Content)` will be ignored.
Test Plan:
Attempt to create repos using swagger on a course with RosterStudents that are part of the organization. If there is a student who is an owner, this will cover the edge case of attempting to give lower than admin permissions to an owner.
Deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/

Customizing Permissions Level on Repos

---

frontend/src/main/pages/HomePageLoggedIn.js
frontend/src/main/utils/useBackend.js
frontend/src/tests/pages/HomePageLoggedIn.test.js
frontend/src/tests/utils/useBackend.test.js

In this PR, I disable the call to `/api/courses/allForInstructors` in useBackend if the user does not have the instructor role.
This can be done with the new parameter to useBackend(queryKey, axiosParams, suppressToasts, **options**) :
any option listed [here](https://tanstack.com/query/latest/docs/framework/react/reference/useQuery) can be used, and will override the ones listed above if necessary.
Deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu
Closes #342

Disabling the Instructor Courses call without the Instructor Role

---

frontend/src/main/components/Courses/InstructorCoursesTable.js
frontend/src/tests/components/Courses/InstructorCoursesTable.test.js

Addresses Issue #318 
- adds a new icon that incorporates a settings and GitHub icon to replace the GitHub icon for the organization/application settings on GitHub in the InstructorCoursesTable.
- edits the tooltips in the InstructorCoursesTable to provide more clarity.
**Storybook**: https://67da6ee1a47bfcdda4700814-btkmgxuvpw.chromatic.com/?path=/story/components-courses-instructorcoursestable--admin-courses-admin-user
**Dokku**: https://frontiers-divyanipunj.dokku-00.cs.ucsb.edu/
- View the new tooltips (for **GitHub Org** and the new **Github Settings Icon**) on InstructorCoursesTable.
- View the new **Github Settings Icon**

divyanipunj - Improved UX on InstructorCoursesTable by updating tooltips and GitHub settings icon.

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CustomErrorController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CustomErrorControllerTests.java

In this PR, I narrow the scope of CustomErrorController to only handle text/html errors so that json errors are properly handled by default Spring Boot error handling. CustomErrorController now extends BasicErrorController to keep this functionality. Tests were tweaked to recieve html output.
Deployed to https://frontiers-qa2.dokku-00.cs.ucsb.edu/

Narrowing the Scope of CustomErrorController

---

keyconvert-localhost.sh

This PR fixes a logic error in the script for setting up application secret key on localhost.
The script was putting in the text at the `START` and `END` of the key twice, resulting in the key being invalid.   Now it works properly.

pc - fix logic error in script for setting up application secret key on localhost

---

frontend/src/main/components/Courses/InstructorCoursesTable.jsx
frontend/src/main/pages/Auth/SignInSuccessPage.jsx
frontend/src/tests/components/Courses/InstructorCoursesTable.test.jsx
src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

This PR addresses #378.
This PR: 
- edits the CoursesController endpoint /api/courses/link and tests to navigate back to the page the user was originally on.
- edits InsturctorCourseTable and tests to save path before redirecting to GitHub. 
dokku: https://frontiers-divyanipunj.dokku-00.cs.ucsb.edu/

divyanipunj - redirects to correct page after linking organization [DRAFT]

---

docs/examples/egrades_with_duplicate_emails.csv
docs/examples/egrades_with_duplicate_ids.csv
docs/examples/egrades_with_email_and_student_ids_from_diff_students.csv
frontend/src/fixtures/rosterStudentFixtures.js
frontend/src/main/components/TabComponent/EnrollmentTabComponent.jsx
frontend/src/stories/components/Courses/InstructorCoursesTable.stories.jsx
frontend/src/tests/components/TabComponent/EnrollmentTabComponent.test.jsx
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java

In this PR, I ensure that roster students submitted by CSV and POST are consistent in the database. When submitted, the method checks if there is already a Roster Student with that email and a Roster Student with that Student ID. If they are the same, it updates them. If they come from different Roster Students, it rejects it. They are then added to the list of rejected Roster Students, for the Instructor to handle.
The frontend will currently fail silently, but this is not a common bug.
1. Clear the Roster Students for a course
2. Upload a roster student with the ID `A123456`
3. Upload a different roster student with the email `cgaucho@ucsb.edu`
4. Try to upload the `egrades.csv`
5. Ensure that the Chris Fake roster student has not been created.
Deployed to: …

Ensuring Student Email and Student ID come from the same Roster Student

---

.devcontainer/production/devcontainer.json
.devcontainer/production/docker-compose.yml
.github/workflows/42-smoke-test.yml
Dockerfile

In this PR, I design a smoke test for proj-frontiers in a production environment. Using a `docker-compose`, I create a container from our Dockerfile and also a postgres environment.
I also add a devcontainer in case any local development would like to be tested in a "production" postgres environment.
As an example of a test for this, see #433 (Example of Smoking for Smoke Test) which adds a bogus database migration.

Creating a Smoke Test

---

frontend/src/main/pages/Instructor/InstructorCourseShowPage.jsx
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.jsx

**Addresses part of #368**. (Will address second part of feature after completing #431)
**This PR:** 
- removes the management tab from InstructorCourseShowPage and adds all the relevant information from the InstructorCoursesTable to the header. 
Deployed to: https://frontiers-divyanipunj.dokku-00.cs.ucsb.edu/
Storybook: https://67da6ee1a47bfcdda4700814-hbgetzzjvn.chromatic.com/?path=/story/pages-instructor-instructorcourseshowpage--example-course-no-students
1. Open the InstructorCoursesShowPage to view the changes made to the header and tab organization. 
2. Make sure that both links in the header work.

 divyanipunj - UX improvement on InstructorCourseShowPage

---

frontend/src/fixtures/rosterStudentFixtures.js
frontend/src/main/components/RosterStudent/DroppedStudentsTable.jsx
frontend/src/main/components/TabComponent/EnrollmentTabComponent.jsx
frontend/src/stories/components/RosterStudent/DroppedStudentsTable.stories.jsx
frontend/src/tests/components/RosterStudent/DroppedStudentsTable.test.jsx
frontend/src/tests/components/TabComponent/EnrollmentTabComponent.test.jsx
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsCSVController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
src/main/java/edu/ucsb/cs156/frontiers/enums/OrgStatus.java
src/main/java/edu/ucsb/cs156/frontiers/jobs/RemoveStudentsJob.java
src/main/java/edu/ucsb/cs156/frontiers/models/LoadResult.java
src/main/java/edu/ucsb/cs156/frontiers/services/UpdateUserService.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsCSVControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
src/test/java/edu/ucsb/cs156/frontiers/jobs/RemoveStudentsJobTests.java
src/test/java/edu/ucsb/cs156/frontiers/services/UpdateUserServiceTests.java

In this PR, I refactor the UpsertResponse method so that the actual saving is handled outside the method. Additionally, the method is refactored to search for students who are present on the course roster student list, as it will cut down on the number of database calls and make the list much easier to handle, as it keeps down the number of objects and means when students are "updated", they are already present on the list of students for the course.
I do so with the intention to allow marking students as dropped from the CSV endpoint without having to refetch students from the database.
Then, I refactor the method to mark students with the RosterStatus `ROSTER` as dropped. It then updates the list with everyone on the roster (updated students update existing object references on the …

Handling Drops
