ucsb-cs156/proj-frontiers

frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/Nav/Footer.js
frontend/src/main/pages/HomePage.js
frontend/src/tests/components/Nav/Footer.test.js

In this PR, I update the branding from Example to Frontiers in the Navbar, and change the homepage message and footer.
New Homepage:

Updating the Frontiers Branding

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/FrontendProxyController.java

In this PR, I add the ability to log into the Backend without a frontend server running.
Closes #14.

Adding Backend-Only Login

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java

In this PR, we add:
* POST method to create course
* GET method to get all courses
Closes #16

pc - add POST and GET in Courses Controller

---

frontend/src/main/components/Nav/AppNavbar.js
frontend/src/main/components/Nav/GoogleLogin.js
frontend/src/stories/components/Nav/AppNavbar.stories.js
frontend/src/stories/components/Nav/GoogleLogin.stories.js

In this PR, we refactor the Google Login button into a separate component.  This is preparation for issue #23

pc - refactor Google Login button into separate component

---

src/main/java/edu/ucsb/cs156/frontiers/FrontiersMain.java
src/main/resources/application.properties

In this PR, we close #30 which is a bug report indicating that the values for the repo and commit at /api/systemInfo are wrong: 
What we observe:
```
{
"springH2ConsoleEnabled": false,
"showSwaggerUILink": true,
"oauthLogin": "/oauth2/authorization/google",
"sourceRepo": "https://github.com/ucsb-cs156-s25/STARTER-team01",
"commitMessage": "unknown",
"commitId": "unknown",
"githubUrl": "https://github.com/ucsb-cs156-s25/STARTER-team01/commit/unknown"
}
```
What we expect:
```
{
"springH2ConsoleEnabled": false,
"showSwaggerUILink": true,
"oauthLogin": "/oauth2/authorization/google",
"sourceRepo": "https://github.com/ucsb-cs156/proj-frontiers",
"commitMessage": "unknown",
"commitId": "5a45474",
"githubUrl": "https://github.com/ucsb-cs156/proj-frontiers/commit/5a45474"
}
```
* Fixing the …

Pc fix GitHub commit info

---

README.md

In this PR, we update the README.md file with information about Frontiers. 
Previously, it had a README that was inherited from the CMPSC 156 team01 assignment code base (this code base branched off of that one.)

pc - update README.md with info about frontiers

---

Dockerfile
startup.sh

In this PR, I add the autoconfiguration script for `JDBC_DATABASE_USERNAME`, `JDBC_DATABASE_URL`, and `JDBC_DATABASE_PASSWORD` that is present in [team01](https://github.com/ucsb-cs156-s25/STARTER-team01) and [team02](https://github.com/ucsb-cs156-s25/STARTER-team02).
Currently deployed to https://proj-frontiers-division7.dokku-00.cs.ucsb.edu/

Adding Postgres Autoconfiguration

---

frontend/src/main/components/Courses/CoursesTable.js
frontend/src/tests/components/Courses/CoursesTable.test.js

This PR fixes formatting and test issues in Ben's PR 
https://github.com/ucsb-cs156/proj-frontiers/pull/91
that fixes the broken Courses Table.

pc - fix formatting and tests in PR 91

---

docs/examples/README.md
docs/examples/egrades.csv
frontend/src/main/components/Courses/CoursesTable.js

- Whitelabel issue when clicking Install Github App
- Used window.location.href instead of navigate as navigate is for client side routes and does not work when using api links that return 302
https://frontiers-bennyyyyy.dokku-00.cs.ucsb.edu/admin/courses

BC - Fixed minor bug when redirecting server side

---

.github/workflows/99-copy-issues.yml

Adds workflow 99 for copying github issues to proj-frontiers

copying workflow99

---

docs/github-app-setup-dokku.md
docs/github-app-setup-localhost.md

In this PR, we clarify the instructions for github app setup.
To see the new changes, look at: 
* <https://github.com/ucsb-cs156/proj-frontiers/blob/pc-github-app-setup-docs/docs/github-app-setup-dokku.md>
* <https://github.com/ucsb-cs156/proj-frontiers/blob/pc-github-app-setup-docs/docs/github-app-setup-localhost.md>

Update github-app-setup-dokku.md to clarify instructions

---

frontend/src/App.js
frontend/src/main/pages/HomePageLoggedOut.js
frontend/src/stories/pages/HomePageLoggedOut.stories.js
frontend/src/tests/pages/HomePageLoggedOut.test.js

- changes all instances of HomePage to HomePageLoggedOut.
- changes the welcome message on the new HomePageLoggedOut page from '_Hello, World!_' to '_Welcome to Frontiers!_'
Storybook: https://67da6ee1a47bfcdda4700814-ayfjhnkari.chromatic.com/?path=/story/pages-homepageloggedout--logged-out
Dokku: https://frontiers-divyanipunj.dokku-00.cs.ucsb.edu/
I do not think any testing is necessary for this PR since it is simply updating the naming convention.

divyanipunj - Changed all instances of HomePage to HomePageLoggedOut.

---

frontend/src/main/components/Courses/CourseModal.js
frontend/src/stories/components/Courses/CourseModal.stories.js
frontend/src/tests/components/Courses/CourseModal.test.js

In this PR, I create a modal to allow the creation and editing of courses. It is currently only visible on storybook.
Example Photo:
Storybook: https://67da6ee1a47bfcdda4700814-ghoiyqeqwv.chromatic.com/?path=/story/components-courses-coursemodal--create
Contributes to #133

Creating a Modal to Create and Edit Courses

---

.github/workflows/42-deploy-dokku.yml

In this PR, I create a workflow to automatically call the workflow in [ucsb-cs156-s25/dokku-sync](https://github.com/ucsb-cs156-s25/dokku-sync) when a PR is labelled with "Dokku Deploy"
Additionally, I've set workflows to require approval to run from anyone except repository members and owners, to prevent malicious code pushes.
Deployed to https://frontiers-daniel.dokku-00.cs.ucsb.edu/

Workflow to Automatically Deploy to Dokku

---

.github/workflows/42-deploy-pr-to-dokku.yml
.github/workflows/43-deploy-main-to-frontiers-prod.yml
.github/workflows/44-deploy-main-to-frontiers-qa.yml

In this PR, we rename the workflow for syncing a PR to dokku, and add two similar workflows for syncing to prod and the main qa deployment.

pc - refactor jobs for deploying to dokku

---

frontend/src/main/components/Assignments/IndividualAssignmentForm.js
frontend/src/main/components/TabComponent/AssignmentTabComponent.js
frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/stories/components/Assignments/IndividualAssignmentForm.stories.js
frontend/src/stories/pages/Instructor/InstructorCourseShowPage.stories.js
frontend/src/tests/components/Assignments/IndividualAssignmentForm.test.js
frontend/src/tests/components/TabComponent/AssignmentTabComponent.test.js
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js

In this PR, I add an `IndividualAssignmentForm` and add it to the `CourseShowPage` under the `AssignmentsTabComponent`, to keep down the test count on the CourseShowPage.
Test Plan:
1. Use the attached course to generate a repository with any prefix for the listed Roster Students
2. See if they show up
Deployed: https://frontiers-qa5.dokku-00.cs.ucsb.edu

Creating a Frontend for Posting Individual Student Repos

---

frontend/src/App.js
frontend/src/main/components/TabComponent/EnrollmentTabComponent.js
frontend/src/main/pages/HomePageLoggedIn.js
frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
frontend/src/tests/components/TabComponent/EnrollmentTabComponent.test.js
frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js

In this PR, I use the rewrite of the `EnrollmentTabComponent` to add the CSV Download button to the row with uploading a course roster and adding an individual student.
Test Plan
1. Have a course with roster students
2. Attempt to download the course CSV. (See course 1)
Deployed to https://frontiers-qa6.dokku-00.cs.ucsb.edu with #322 .
Closes #36 .

Adding a CSV download button

---

frontend/src/fixtures/csvFixtures.js
frontend/src/index.css
frontend/src/main/pages/Help/HelpAboutPage.js
frontend/src/main/pages/Help/HelpCsvPage.js
frontend/src/stories/pages/Help/HelpAboutPage.stories.js
frontend/src/stories/pages/Help/HelpCSVPage.stories.js
frontend/src/tests/pages/Admin/AdminsIndexPage.test.js
frontend/src/tests/pages/Help/HelpAboutPage.test.js
frontend/src/tests/pages/Help/HelpCsvPage.test.js

MERGE AFTER #333 
In this PR, we fill in content on the Help/About page.
Deployed to: https://frontiers-qa8.dokku-00.cs.ucsb.edu
* <https://ucsb-cs156.github.io/proj-frontiers/prs/334/chromatic>
* Navigate to Help Pages
1. Visit <https://frontiers-qa8.dokku-00.cs.ucsb.edu>
2. Access help menu items
3. See documentation

Fill in Help / About page.

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLController.java
src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java

In this PR, I ensure that API endpoints are properly gated behind the appropriate level of authentication to prevent any FERPA violations.
This time, I correct the annotations as necessary.
Deployed to https://frontiers-daniel.dokku-00.cs.ucsb.edu/

Fixing FERPA annotations

---

.github/workflows/02-gh-pages-rebuild-part-1.yml
.github/workflows/10-backend-unit.yml
.github/workflows/12-backend-jacoco.yml
.github/workflows/13-backend-incremental-pitest.yml
.github/workflows/14-backend-pitest.yml
.github/workflows/15-backend-format.yml
.github/workflows/40-check-production-build.yml
.github/workflows/41-integration.yml
.github/workflows/56-javadoc-main-branch.yml
.github/workflows/58-javadoc-pr.yml

* add -ntp to mvn commands to reduce unnecessary and distracting output
* fix broken code to determine output path for updates to github pages site for PRs

pc - fix issues in workflows

---

.github/workflows/01-gh-pages-pr-table.yml
.github/workflows/02-gh-pages-rebuild-part-1.yml
.github/workflows/04-gh-pages-redeploy-part-2.yml
.github/workflows/10-backend-unit.yml
.github/workflows/12-backend-jacoco.yml
.github/workflows/13-backend-incremental-pitest.yml
.github/workflows/14-backend-pitest.yml
.github/workflows/15-backend-format.yml
.github/workflows/32-frontend-coverage.yml
.github/workflows/33-frontend-pr-mutation-testing.yml
.github/workflows/34-frontend-main-mutation-testing.yml
.github/workflows/36-frontend-eslint.yml
.github/workflows/40-check-production-build.yml
.github/workflows/41-integration.yml
.github/workflows/56-javadoc-main-branch.yml
.github/workflows/58-javadoc-pr.yml
.github/workflows/82-kanban-slack-update.yml
.github/workflows/99-copy-issues.yml

In this PR, we update the workflows to be consistent with proj-dining, and to rely on updated versions of many workflows.

pc - update workflows for consistency with dining, and updated dependencies

---

.github/workflows/01-gh-pages-pr-table.yml

In this PR, we convert workflow 01 to call a reusable workflow from the repo https://github.com/ucsb-cs156/workflows
The idea is to DRY up (don't repeat yourself) our workflows, so that if/when we want to fix a bug, or add a feature, we only have to do it in on place, rather than across dozens of individual repos.

Convert workflow 01 to a reusable workflow

---

.github/workflows/00-all-checks-pass.yml
.github/workflows/01-gh-pages-pr-table.yml
.github/workflows/10-backend-unit.yml

In this PR, we convert workflows 00, 01 and 10 to call a reusable workflow from the repo https://github.com/ucsb-cs156/workflows
The idea is to DRY up (don't repeat yourself) our workflows, so that if/when we want to fix a bug, or add a feature, we only have to do it in on place, rather than across dozens of individual repos.
We originally tried this in PR #418, but we got it wrong.  This PR fixes that.
If this works, we'll add a few more workflows a few at a time in future PRs until we've converted as many as possible.

Convert workflows 00, 01 and 10 to reusable workflows from repo https://github.com/ucsb-cs156/workflows

---

src/main/java/edu/ucsb/cs156/frontiers/controllers/TeamsController.java
src/test/java/edu/ucsb/cs156/frontiers/controllers/TeamsControllerTests.java

In this PR, I modify the `uploadTeamsCsv` method to return an HTTP 409 if there are any lines in the CSV that do not have a matching roster student.
This will make this easier to respond to on the frontend.
Deployed to https://frontiers-qa4.dokku-00.cs.ucsb.edu/

Team Csv lines without valid roster students now return a 409

---

frontend/src/fixtures/rosterStudentFixtures.js
frontend/src/main/components/RosterStudent/DroppedStudentsTable.jsx
frontend/src/main/components/TabComponent/EnrollmentTabComponent.jsx
frontend/src/stories/components/RosterStudent/DroppedStudentsTable.stories.jsx
frontend/src/tests/components/RosterStudent/DroppedStudentsTable.test.jsx
frontend/src/tests/components/TabComponent/EnrollmentTabComponent.test.jsx

In this PR, I add a table of dropped students as a possible example of what one implementation could look like.
Deployed to https://frontiers-qa7.dokku-00.cs.ucsb.edu

Adding a Table of Dropped Students
